CListEvent for roots
pkhateri/STIR pull request #8
Opened 2022-01-17 14:42 UTC by VietAnhDao

1. Adjusted CListEvent for root files.

- Stored ProjDataInfo instead of ProjDataInfoCylindrical.

- Downcast ProjDataInfo to correct geometry when needed.

2. Added crystal map option for randoms.

- If crystal map is defined in Interfile header then STIR will shift the order of singles with respect to mapping between internal and external crystal.

NOTE: test attempted but warning occurred. When converting root to projdata, STIR cannot find position in internal crystal map. Similarly with randoms.

2022-01-17 14:43 UTC, VietAnhDao commented
@KrisThielemans , @emikhay , @danieldeidda .

2022-01-25 11:08 UTC, KrisThielemans requested changes
looks good overall. a bit ugly that we have to repeat the code. This can be done a bit cleaner maybe (with some template  stuff) but the main worry is usage of
```
this->proj_data_info_sptr->get_scanner_ptr()->get_scanner_geometry()== "BlocksOnCylindrical"
```
etc in every call. This is potentially somewhat computationally involved, while it'll be called for every listmode event, so could slow things down a bit.

i suggest to create a private `enum scanner_type {CYL,BLOCK,GENERIC}`, initialise this in the constructor, and then use
```c++
switch (scanner_type)
  case:CYL: code; break;
  case BLOCK: code break;
  case GENERIC: code;break;
}
```

Also, the `shift` will now be necessary in the block/generic cases as well after @danieldeidda's changes, but let's first fix the above. Then we can add the shift code (after a merge of `master` here)

2022-01-25 11:08 UTC, KrisThielemans commented on src/utilities/construct_randoms_from_singles.cxx
> +  }
not sure I understand this code (ok, I don't understand it!), but
- it doesn't have anything to do with ROOT
- it is probably going to be made obsolete by work from @danieldeidda on removing re-ordering.

Therefore, please revert all changes to `construct_randoms_from_singles.cxx` for this PR

2022-01-25 11:08 UTC, KrisThielemans commented on src/include/stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.inl
> +  auto proj_data_info_ptr = this->proj_data_info_sptr;
delete. not used, and confusion

2022-01-25 13:40 UTC, KrisThielemans commented
> NOTE: test attempted but warning occurred. When converting root to projdata, STIR cannot find position in internal crystal map. Similarly with randoms.

not sure what you mean with that.

2022-01-26 15:23 UTC, VietAnhDao commented
> > NOTE: test attempted but warning occurred. When converting root to projdata, STIR cannot find position in internal crystal map. Similarly with randoms.
> 
> not sure what you mean with that.

please ignore, I forgot to return the correct type when calling '''get_uncompressed_proj_data_info_sptr()''' and therefore it gives warning can't find the internal crystal (because there is no crystal map). This is fixed now and I've test it with a root file.

2022-02-19 12:06 UTC, KrisThielemans approved these changes
Sorry. I should have merged this first before merging the main PR. Can you please make a PR to UCL/STIR? There's a few ways:
- maybe you can just tell github
- you abandon this PR and create a new one

Would you mind if I then squash-merge it?

2022-02-19 14:55 UTC, VietAnhDao commented
Went with option 2 and I don't mind quash-merge 👍

2022-02-19 14:55 UTC, closed without merging